baseURL = 'https://kalmas.net/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = "Kyle Almas"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[services]
  [services.googleAnalytics]
    id = "G-3B12G4MQVN"

[params.author]
  name = "Kyle Almas"
  headline = "Software Engineer"
  image = "img/kalmas.jpeg"

  links = [
    { linkedin = "https://www.linkedin.com/in/kylealmas" },
    { github = "https://github.com/kalmas" },
    { resume = { href = "doc/Kyle_Almas_Resume.pdf", text = "Resume" } },
    { stack-overflow = "https://stackoverflow.com/users/1361980/kalmas" },
    { instagram = "https://www.instagram.com/kawlmas" },
    { email = "mailto:kylealmas@gmail.com" },
  ]

