baseURL = 'https://example.org/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = "Kyle Almas"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
name = "Kyle Almas"
headline = "Software Engineer"
image = "img/IMG_3281.jpeg"

links = [
    { linkedin = "https://www.linkedin.com/in/kylealmas" },
    { github = "https://github.com/kalmas" },
    { link = { href = "https://github.com/kalmas/resume/blob/main/kyle-almas.pdf", text = "Resume" } },
    { stack-overflow = "https://stackoverflow.com/users/1361980/kalmas" },
    { instagram = "https://www.instagram.com/kawlmas" },
    { email = "mailto:kylealmas@gmail.com" },
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
